### ISSUE TITLE
npm audit security report

### ISSUE THREAD

**Issue by woosungchoi** [JoseRFelix/nextjs-starter-blog#2]
Details
CVE-2020-7661
moderate severity
Vulnerable versions: <= 5.0.0
Patched version: No fix
all versions of url-regex are vulnerable to Regular Expression Denial of Service. An attacker providing a very long string in String.test can cause a Denial of Service.

**Comment by JoseRFelix** [comment]
Currently, a fix for this is not available. However, this won't affect the blog since the dependency is only used on lqip-loader, meaning on build time. Also unless you are giving your images a string to cause this problem it won't result in DDOS. 

If you know any alternative to lqip-loader please let me know.

**Comment by woosungchoi** [comment]
https://hangindev.com/blog/create-a-lazy-loading-image-component-with-react-hooks

I hangindev has something different method.

**Comment by woosungchoi** [comment]
> Currently, a fix for this is not available. However, this won't affect the blog since the dependency is only used on lqip-loader, meaning on build time. Also unless you are giving your images a string to cause this problem it won't result in DDOS.
> 
> If you know any alternative to lqip-loader please let me know.

https://github.com/wix/stylable/commit/2348f705871c9c5c6acfcae0693bb2c33f3d17b8

https://github.com/asteffey/url-shortener-microservice/commit/20519252f325cdfa304df470bdc57e5735cc9397

I think these commits can help you.

**Comment by JoseRFelix** [comment]
Thanks for your comment! I'll be looking into lazy loading with hooks and evaluate its repercussions; again, thanks for the link.

As for URLs It won't affect this codebase directly since the user won't be giving strings for URLs. However, definitely this must be fixed. Since I don't have access to the method directly, I would have to open a PR for `lqip-loader` in order to change their dependency.
